# -*- coding: utf-8 -*-
"""Making the Most of your Colab Subscription

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/pro.ipynb
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pmdarima import auto_arima
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from io import BytesIO

# =========================================================
# PAGE CONFIG
# =========================================================
st.set_page_config(
    page_title="FinanceWise Dashboard",
    page_icon="💰",
    layout="wide"
)

# =========================================================
# SIDEBAR NAVIGATION
# =========================================================
st.sidebar.title("📌 Navigator")
page = st.sidebar.radio(
    "Go to",
    ["📂 Category Analysis", "🔮 Expense and Savings Forecast"]
)
# ---- GLOBAL FILE UPLOAD (SHARED) ----
uploaded_file = st.sidebar.file_uploader(
    "Upload PhonePe Transactions (CSV / Excel)",
    ["csv", "xlsx"]
)

if uploaded_file is not None:
    st.session_state["uploaded_file"] = uploaded_file


# =========================================================
# ================= CATEGORY ANALYSIS =====================
# =========================================================
if page == "📂 Category Analysis":

    st.title("📂 FinanceWise Mentor – Category Analysis")

    uploaded_file = st.file_uploader(
        "Upload PhonePe CSV / Excel",
        ["csv", "xlsx"]
    )

    if uploaded_file is None:
        st.info("Upload your PhonePe transaction file to continue")
        st.stop()

    df = pd.read_csv(uploaded_file) if uploaded_file.name.endswith(".csv") else pd.read_excel(uploaded_file)

    # ---------------- RULE ENGINE ----------------
    def rule_based_category(text):
        t = str(text).lower()
        if "received from" in t or "credited" in t or "salary" in t:
            return "Income"
        if any(x in t for x in ["grocery", "bigbasket", "dmart", "supermarket"]):
            return "Groceries"
        if any(x in t for x in ["electric", "water", "gas", "recharge", "jio", "airtel"]):
            return "Utilities"
        if any(x in t for x in ["uber", "ola", "rapido", "metro"]):
            return "Transport"
        if any(x in t for x in ["amazon", "flipkart", "myntra"]):
            return "Shopping"
        if any(x in t for x in ["zomato", "swiggy", "food", "restaurant"]):
            return "Food"
        if any(x in t for x in ["emi", "loan", "credit card"]):
            return "EMI / Loans"
        return "Other"

    def train_category_model(df, details_col):
        texts = df[details_col].astype(str)
        labels = texts.apply(rule_based_category)
        train_df = pd.DataFrame({"text": texts, "label": labels})
        train_df = train_df[train_df["label"] != "Other"]

        if train_df["label"].nunique() < 2:
            return None, None

        vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1, 2), min_df=2)
        X = vectorizer.fit_transform(train_df["text"])
        model = LogisticRegression(max_iter=2000)
        model.fit(X, train_df["label"])
        return vectorizer, model

    def categorize_transactions(df, details_col):
        df["Category"] = df[details_col].apply(rule_based_category)
        vectorizer, model = train_category_model(df, details_col)

        if vectorizer is None:
            return df

        X = vectorizer.transform(df[details_col].astype(str))
        preds = model.predict(X)
        probs = model.predict_proba(X).max(axis=1)

        final = [
            pred if prob >= 0.6 else rule_based_category(text)
            for text, pred, prob in zip(df[details_col], preds, probs)
        ]

        df["Category"] = final
        return df

    details_col = next(c for c in df.columns if "transaction" in c.lower())
    amount_col = next(c for c in df.columns if "amount" in c.lower())

    df = categorize_transactions(df, details_col)

    # ---------------- METRICS ----------------
    income = df[df["Category"] == "Income"][amount_col].sum()
    expense = df[df["Category"] != "Income"][amount_col].sum()
    savings_rate = ((income - expense) / income * 100) if income > 0 else 0

    c1, c2, c3 = st.columns(3)
    c1.metric("Income", f"₹{income:,.0f}")
    c2.metric("Expense", f"₹{expense:,.0f}")
    c3.metric("Savings Rate", f"{savings_rate:.2f}%")

    st.subheader("📊 Category-wise Spending")
    st.bar_chart(
        df[df["Category"] != "Income"]
        .groupby("Category")[amount_col]
        .sum()
    )

    st.subheader("📄 Categorized Transactions")
    st.dataframe(df)

    # ---------------- DOWNLOAD ----------------
    st.subheader("⬇️ Download Categorized File")
    buffer = BytesIO()
    with pd.ExcelWriter(buffer, engine="xlsxwriter") as writer:
        df.to_excel(writer, index=False)

    st.download_button(
        "Download Excel",
        buffer.getvalue(),
        "categorized_transactions.xlsx",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

# =========================================================
# ============ EXPENSE & SAVINGS FORECAST =================
# =========================================================
elif page == "🔮 Expense and Savings Forecast":

    st.title("🔮 Expense and Savings Forecast (ARIMA)")

    # ✅ USE ALREADY UPLOADED FILE FROM SIDEBAR
    if "uploaded_file" not in st.session_state:
        st.warning("Please upload the PhonePe Excel file from the sidebar")
        st.stop()

    uploaded_file = st.session_state["uploaded_file"]


    df = pd.read_excel(uploaded_file)
    df["Date"] = pd.to_datetime(df["Date"])

    df["Signed Amount"] = np.where(
        df["Type"].str.lower() == "credit",
        df["Amount"],
        -df["Amount"]
    )

    monthly_income = (
        df[df["Signed Amount"] > 0]
        .groupby(pd.Grouper(key="Date", freq="M"))["Signed Amount"]
        .sum()
    )

    monthly_expense = (
        df[df["Signed Amount"] < 0]
        .groupby(pd.Grouper(key="Date", freq="M"))["Signed Amount"]
        .sum()
        .abs()
    )

    monthly_savings = monthly_income - monthly_expense

    c1, c2, c3 = st.columns(3)
    c1.metric("Total Income", f"₹{monthly_income.sum():,.0f}")
    c2.metric("Total Expense", f"₹{monthly_expense.sum():,.0f}")
    c3.metric("Total Savings", f"₹{monthly_savings.sum():,.0f}")

    expense_model = auto_arima(monthly_expense, seasonal=False, suppress_warnings=True)
    income_model = auto_arima(monthly_income, seasonal=False, suppress_warnings=True)

    expense_fc = expense_model.predict(3)
    income_fc = income_model.predict(3)
    savings_fc = income_fc - expense_fc

    forecast_df = pd.DataFrame({
        "Month": ["Next Month", "Month +2", "Month +3"],
        "Predicted Income (₹)": income_fc.round(2),
        "Predicted Expense (₹)": expense_fc.round(2),
        "Predicted Savings (₹)": savings_fc.round(2)
    })

    st.subheader("📈 Forecast Table")
    st.table(forecast_df)

    future_idx = pd.date_range(
        start=monthly_expense.index[-1] + pd.offsets.MonthEnd(1),
        periods=3,
        freq="M"
    )

    st.subheader("📉 Expense Forecast")
    fig1, ax1 = plt.subplots(figsize=(10, 4))
    ax1.plot(monthly_expense.index, monthly_expense, label="Historical")
    ax1.plot(future_idx, expense_fc, "--o", label="Forecast")
    ax1.legend()
    st.pyplot(fig1)

    st.subheader("💰 Savings Forecast")
    fig2, ax2 = plt.subplots(figsize=(10, 4))
    ax2.plot(monthly_savings.index, monthly_savings, label="Historical")
    ax2.plot(future_idx, savings_fc, "--o", label="Forecast")
    ax2.legend()
    st.pyplot(fig2)





